### ISSUE TITLE
(Ipek) As a developer, I would like to develop a backend providing APIs over HTTP to manage the automation

### ISSUE THREAD

**Issue by cagdasgerede** [tobbetu-ceng-industry-collaborations/smarteff-main#7]
This component should provide APIs over HTTP.

The features it should support are as follows:

# ListUsers
An API endpoint to list users in the system. This should access the database and retrieve the list of users in the system and return them. The call should return <person id, person name> pairs so that the name can be used to visualize the person in a ui while the id can be used in the consecutive calls from the client.

The return data should be a JSON similar to :

```
{
  people : [
    {
     name: "ali",
     id: "10"
    },
    {
     name: "veli",
     id: "25"
    },
    {
     name: "ayse",
     id: "37"
    }
  ]
}
```

# ListDevices
An API endpoint to list device information for a given user. The information should contain the names and ids of the devices used by the user. In addition, it should have an indication whether each device is on or off. Moreover, it should have the information about whether the automated shutdown is enabled or suspended for each device.

Example command line call:
```
curl -i -H "Accept: application/json" -H "Content-Type: application/json" -X GET http://hostname/ListDevices?UserId=123
```

Example output:

```
{
  devices: [
    {
      name: "D9123",
      id: "32",
      isOn: "true",
      automation : {
        suspended: "true",
        expiration: "15 January 20:00pm 2020"
      }
    },
    {
      name: "D9043",
      id: "45",
      isOn: "true",
      automation : {
        suspended: "false"
      }
    },
    {
      name: "D4120",
      id: "29",
      isOn: "false",
      automation : {
        suspended: "false",
      }
    }
  ]
}
```

# ListScheduledShutdowns
An API endpoint to list suspensions for a user.

```
curl -i -H "Accept: application/json" -H "Content-Type: application/json" -X GET http://hostname/ListScheduledShutdowns?UserId=123
```

```
{
  scheduledShutdowns: [
    {
      device: {
        name: "D9123",
        id: "123",
      },
      timestamp: "20:00pm 20 January 2020"
    },
    {
      device: {
        name: "D324",
        id: "993",
      },
      timestamp: "20:00pm 20 January 2020"
    }
  ]
}
```

**Comment by BaturayOnural** [comment]
Currently all of the endpoints should be working, and ready to be integrated with other components. The table explaining API calls is provided as well.

[Smarteff.REST.API.Calls.1.pdf](https://github.com/tobbetu-ceng-industry-collaborations/smarteff-main/files/4279943/Smarteff.REST.API.Calls.1.pdf)
